application: Force Chat Example 
version: 1
deploy: true
pub: true
dart2js: true 
framework: force

handlers:
- url: /
  script: server.dart

# Static content, will be served by your app's Nginx instance   
- url: /
  match: preregex
  static_dir: web
  
